### ISSUE TITLE
Rewrite generation scripts in Go

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-sdk-go#85]
The Bash script are difficult to work with and maintain. We need to use a programming language to give proper error handling.

**Comment by wtrocki** [comment]
Out of curiosity. What is not working well?

so we will have:

- Go wrapper for 
- Node.js wrapper 
- That runs java processes :)

**Comment by wtrocki** [comment]
I found this strange because CLI PR was closed and that would have used Node.js CLI as package cutting another layer and in fact simplifying error handling.  There are numerous downsides of using go:

- you need to compile it and build it (not every SDK will have go setup)
- We need to release it somehow to be used
- We going to call out separate process so not getting argument about error handling - we are still limited to error codes returned by process.

https://github.com/redhat-developer/app-services-sdk-js/blob/main/scripts/generate.sh

**Comment by craicoverflow** [comment]
The Bash scripts are incredibly limiting - having to mix use Node.js and Bash to dynamically load values from a config file because there is no easier way.

> you need to compile it and build it (not every SDK will have go setup)

It will be as simple as `go get -u github.com/redhat-developer/app-services-sdk-go/internal/apigen/cmd/api-fetch` to install, once Golang is installed - no need to compile manually.

> We need to release it somehow to be used

It is very easy to release in Go - a tag.

> We going to call out a separate process so not to get an argument about error handling - we are still limited to error codes returned by the process.

We can codify everything apart from openapi-generator. I have a TODO to use the Go-Git client.

> Out of curiosity. What is not working well?

With this approach, I can incorporate the creation of the pull request into the Go code and give better messages etc.

**Comment by craicoverflow** [comment]
> Even kubernetes uses bash for releng

Okay, but others use code - like Google Cloud SDKs - https://github.com/googleapis/google-cloud-go/tree/master/internal/gapicgen
